version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm-version
          name: check-npm-version1
          command: npm version
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: npm-version
          name: check-npm-version2
          command: npm version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: release
          command: npm run semantic-release